import Header from "../components/Header";
import Footer from "../components/Footer";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    default: "Next.js Tutorial - Codeevolution",
    template: "%s | codeevolution",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  // return (
  //   <html lang="en">
  //     <body>
  //       <header
  //         style={{
  //           backgroundColor: "lightblue",
  //           padding: "1rem",
  //         }}
  //       >
  //         <p>Header</p>
  //       </header>
  //       {children}
  //       <footer
  //         style={{
  //           backgroundColor: "ghostwhite",
  //           padding: "1rem",
  //         }}
  //       >
  //         <p>Footer</p>
  //       </footer>
  //     </body>
  //   </html>
  // );
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
